### ISSUE TITLE
TTS 崩溃

### ISSUE THREAD

**Issue by FHangH** [Circle1688/XunFeiTTS#1]
流式TTS没问题，但我用OnFinish和SoundWave播放合成好的soundwav会崩溃
![image](https://github.com/Circle1688/XunFeiTTS/assets/49579735/fa7e044a-a494-4dc5-8788-5c75bef776ba)
![image](https://github.com/Circle1688/XunFeiTTS/assets/49579735/8ce53f65-e9fd-4b35-acdc-446f378f3e3d)

**Comment by FHangH** [comment]
然后我用了委曲求全的方式，暂时解决了这个问题
![image](https://github.com/Circle1688/XunFeiTTS/assets/49579735/1b7ceb00-3f1e-40af-bc45-2d1f629b20b1)

**Comment by Circle1688** [comment]
问题排查中，音频过长会导致这个问题，应该跟缓冲区有关。
暂时的办法：请在OnFinish时将Streaming Sound Wave提升为变量使用

**Comment by Circle1688** [comment]
已更新仓库，取消了Sound Wave这个参数，使用Stream Sound Wave即可
