### ISSUE TITLE
打包到安卓后运行TTS会闪退

### ISSUE THREAD

**Issue by lv107** [Circle1688/XunFeiTTS#2]
![@%@9X8AXCHE6VH0BPKLS~1O](https://github.com/Circle1688/XunFeiTTS/assets/147241550/ac9b1df6-a485-40d7-9e5e-e21af166be12)
引擎版本是5.1 这是手机的对他的崩溃日志

**Comment by Circle1688** [comment]
没有在安卓上测试过
